version: '2'
services:
  jandall-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/jandall/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jandall
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
